# Added to get rid of [WARN] messages on startup
command_timeout = 1000

# Change the default prompt format
format = """\
[╭╴](238)$env_var\
$all[╰─](238)$character"""

# Change the default prompt characters
[character]
success_symbol = "[](238)"
error_symbol = "[](238)"

# Shows the OS icon and Username from powershell $PROFILE
[env_var.STARSHIP_DISTRO]
format = '[$env_value](bold white)'
variable = "STARSHIP_DISTRO"
disabled = false

# Show the username
[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = true
show_always = false

[python]
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = ' '
pyenv_version_name = false
pyenv_prefix = 'pyenv'
detect_extensions = ["py"]
detect_files = [
				".python-version",
				"Pipfile",
				"__init__.py",
				"pyproject.toml",
				"requirements.txt",
				"setup.py",
				"tox.ini"
				]